controller:
  ingressClassResource:
    name: nginx-internal # default: nginx
    enabled: true
    default: false
    controllerValue: "k8s.io/ingress-nginx-internal"
  service:
    loadBalancerIP: 10.10.0.112
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"