apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-tls-spc-app-07
spec:
  provider: azure
  secretObjects: # k8s secret
  - secretName: tls-secret-csi-app-07
    type: kubernetes.io/tls
    data: 
    - objectName: aks-ingress-cert
      key: tls.key
    - objectName: aks-ingress-cert
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    userAssignedIdentityID: ""
    clientID: "75d8e078-d9a7-4a4c-b75e-d18225377711" # Setting this to use workload identity
    keyvaultName: kv4aks2302 # the name of the AKV instance
    objects: |
      array:
        - |
          objectName: aks-ingress-cert
          objectType: secret
    tenantId: "9d427af2-14f5-4a21-ad29-9bf8683da155" # the tenant ID for KV
