apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: "75d8e078-d9a7-4a4c-b75e-d18225377711"
  labels:
    azure.workload.identity/use: "true"
  name: workload-identity-sa
